#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantilla.core.Entities
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;


	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name = "PS_ORDENES_PRODUCCION")]
	public partial class PlantillaDataContext : System.Data.Linq.DataContext
	{

		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();

		#region Definiciones de métodos de extensibilidad
		partial void OnCreated();
		partial void InsertESTADOS_DEMO(ESTADOS_DEMO instance);
		partial void UpdateESTADOS_DEMO(ESTADOS_DEMO instance);
		partial void DeleteESTADOS_DEMO(ESTADOS_DEMO instance);
		#endregion

		public PlantillaDataContext() :
				base(global::Plantilla.core.Properties.Settings.Default.PS_ORDENES_PRODUCCIONConnectionString, mappingSource)
		{
			OnCreated();
		}

		public PlantillaDataContext(string connection) :
				base(connection, mappingSource)
		{
			OnCreated();
		}

		public PlantillaDataContext(System.Data.IDbConnection connection) :
				base(connection, mappingSource)
		{
			OnCreated();
		}

		public PlantillaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
				base(connection, mappingSource)
		{
			OnCreated();
		}

		public PlantillaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
				base(connection, mappingSource)
		{
			OnCreated();
		}

		public System.Data.Linq.Table<ESTADOS_DEMO> ESTADOS_DEMOs
		{
			get
			{
				return this.GetTable<ESTADOS_DEMO>();
			}
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_OBT_ORDENES_PRODUCCION_FILTRO")]
		public ISingleResult<PROC_OBT_ORDENES_PRODUCCION_FILTROResult> PROC_OBT_ORDENES_PRODUCCION_FILTRO([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_ORDENES_PRODUCCION_FILTROResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_OBT_USUARIOS_ORDENES_PRODUCCION_FILTRO")]
		public ISingleResult<PROC_OBT_USUARIOS_ORDENES_PRODUCCION_FILTROResult> PROC_OBT_USUARIOS_ORDENES_PRODUCCION_FILTRO([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_USUARIOS_ORDENES_PRODUCCION_FILTROResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_OBT_SIGUIENTE_CONSECUTIVO_ORDENES_PRODUCCION")]
		public ISingleResult<PROC_OBT_SIGUIENTE_CONSECUTIVO_ORDENES_PRODUCCIONResult> PROC_OBT_SIGUIENTE_CONSECUTIVO_ORDENES_PRODUCCION([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_SIGUIENTE_CONSECUTIVO_ORDENES_PRODUCCIONResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_OBT_BODEGAS")]
		public ISingleResult<PROC_OBT_BODEGASResult> PROC_OBT_BODEGAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_BODEGASResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_OBT_ARTICULOS_A_PRODUCIR")]
		public ISingleResult<PROC_OBT_ARTICULOS_A_PRODUCIRResult> PROC_OBT_ARTICULOS_A_PRODUCIR([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_ARTICULOS_A_PRODUCIRResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_OBT_ULTIMA_ORDEN_PRODUCCION")]
		public ISingleResult<PROC_OBT_ULTIMA_ORDEN_PRODUCCIONResult> PROC_OBT_ULTIMA_ORDEN_PRODUCCION([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_ULTIMA_ORDEN_PRODUCCIONResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_OBT_CENTROS_DE_COSTO")]
		public ISingleResult<PROC_OBT_CENTROS_DE_COSTOResult> PROC_OBT_CENTROS_DE_COSTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_CENTROS_DE_COSTOResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_OBT_CUENTAS_CONTABLES")]
		public ISingleResult<PROC_OBT_CUENTAS_CONTABLESResult> PROC_OBT_CUENTAS_CONTABLES([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_CUENTAS_CONTABLESResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_OBT_ARTICULOS_A_CONSUMIR")]
		public ISingleResult<PROC_OBT_ARTICULOS_A_CONSUMIRResult> PROC_OBT_ARTICULOS_A_CONSUMIR([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_ARTICULOS_A_CONSUMIRResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_DEL_ORDEN_PRODUCCION_LINEA")]
		public int PROC_DEL_ORDEN_PRODUCCION_LINEA([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "DOCUMENTO", DbType = "VarChar(50)")] string dOCUMENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "LINEA", DbType = "Int")] System.Nullable<int> lINEA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dOCUMENTO, lINEA, cIA);
			return ((int)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_DEL_ORDEN_PRODUCCION")]
		public int PROC_DEL_ORDEN_PRODUCCION([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "DOCUMENTO", DbType = "VarChar(50)")] string dOCUMENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dOCUMENTO, cIA);
			return ((int)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_OBT_CUENTAS_CONTABLES_X_CENTRO_COSTO")]
		public ISingleResult<PROC_OBT_CUENTAS_CONTABLES_X_CENTRO_COSTOResult> PROC_OBT_CUENTAS_CONTABLES_X_CENTRO_COSTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CENTRO_COSTO", DbType = "VarChar(25)")] string cENTRO_COSTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cENTRO_COSTO, cIA);
			return ((ISingleResult<PROC_OBT_CUENTAS_CONTABLES_X_CENTRO_COSTOResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_EDI_APROBAR_ORDEN_PRODUCCION")]
		public int PROC_EDI_APROBAR_ORDEN_PRODUCCION([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "DOCUMENTO", DbType = "VarChar(50)")] string dOCUMENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "USUARIO", DbType = "VarChar(50)")] string uSUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dOCUMENTO, uSUARIO, cIA);
			return ((int)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_EDI_BODEGA_ORDEN_PRODUCCION_LINEA")]
		public int PROC_EDI_BODEGA_ORDEN_PRODUCCION_LINEA([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "DOCUMENTO", DbType = "VarChar(50)")] string dOCUMENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "LINEA", DbType = "Int")] System.Nullable<int> lINEA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "BODEGA", DbType = "VarChar(4)")] string bODEGA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dOCUMENTO, lINEA, bODEGA, cIA);
			return ((int)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_EDI_CANTIDAD_ORDEN_PRODUCCION_LINEA")]
		public int PROC_EDI_CANTIDAD_ORDEN_PRODUCCION_LINEA([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "DOCUMENTO", DbType = "VarChar(50)")] string dOCUMENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "LINEA", DbType = "Int")] System.Nullable<int> lINEA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CANTIDAD", DbType = "Decimal(28,8)")] System.Nullable<decimal> cANTIDAD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dOCUMENTO, lINEA, cANTIDAD, cIA);
			return ((int)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_EDI_CENTRO_COSTO_ORDEN_PRODUCCION_LINEA")]
		public int PROC_EDI_CENTRO_COSTO_ORDEN_PRODUCCION_LINEA([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "DOCUMENTO", DbType = "VarChar(50)")] string dOCUMENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "LINEA", DbType = "Int")] System.Nullable<int> lINEA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CENTRO_COSTO", DbType = "VarChar(25)")] string cENTRO_COSTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dOCUMENTO, lINEA, cENTRO_COSTO, cIA);
			return ((int)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_EDI_CUENTA_CONTABLE_ORDEN_PRODUCCION_LINEA")]
		public int PROC_EDI_CUENTA_CONTABLE_ORDEN_PRODUCCION_LINEA([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "DOCUMENTO", DbType = "VarChar(50)")] string dOCUMENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "LINEA", DbType = "Int")] System.Nullable<int> lINEA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CUENTA_CONTABLE", DbType = "VarChar(25)")] string cUENTA_CONTABLE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dOCUMENTO, lINEA, cUENTA_CONTABLE, cIA);
			return ((int)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_OBT_BODEGAS_X_ARTICULO")]
		public ISingleResult<PROC_OBT_BODEGAS_X_ARTICULOResult> PROC_OBT_BODEGAS_X_ARTICULO([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "ARTICULO", DbType = "VarChar(20)")] string aRTICULO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aRTICULO, cIA);
			return ((ISingleResult<PROC_OBT_BODEGAS_X_ARTICULOResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_OBT_EXISTENCIAS_X_ARTICULO")]
		public ISingleResult<PROC_OBT_EXISTENCIAS_X_ARTICULOResult> PROC_OBT_EXISTENCIAS_X_ARTICULO([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "ARTICULO", DbType = "VarChar(20)")] string aRTICULO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "BODEGA", DbType = "VarChar(4)")] string bODEGA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aRTICULO, bODEGA, cIA);
			return ((ISingleResult<PROC_OBT_EXISTENCIAS_X_ARTICULOResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_OBT_USUARIOS")]
		public ISingleResult<PROC_OBT_USUARIOSResult> PROC_OBT_USUARIOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "ROL", DbType = "Int")] System.Nullable<int> rOL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rOL, cIA);
			return ((ISingleResult<PROC_OBT_USUARIOSResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_EDI_ESTADO_USUARIO")]
		public int PROC_EDI_ESTADO_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "USUARIO", DbType = "VarChar(50)")] string uSUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "ESTADO", DbType = "VarChar(1)")] string eSTADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSUARIO, eSTADO, cIA);
			return ((int)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_OBT_ROLES")]
		public ISingleResult<PROC_OBT_ROLESResult> PROC_OBT_ROLES([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_ROLESResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_EDI_USUARIO")]
		public int PROC_EDI_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "USUARIO", DbType = "VarChar(50)")] string uSUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "ROL", DbType = "Int")] System.Nullable<int> rOL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSUARIO, rOL, cIA);
			return ((int)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_EDI_DESCRIPCION_ROL")]
		public int PROC_EDI_DESCRIPCION_ROL([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "ROL", DbType = "Int")] System.Nullable<int> rOL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "DESCRIPCION", DbType = "VarChar(200)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rOL, dESCRIPCION, cIA);
			return ((int)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_OBT_USUARIOS_PARA_INSERTAR")]
		public ISingleResult<PROC_OBT_USUARIOS_PARA_INSERTARResult> PROC_OBT_USUARIOS_PARA_INSERTAR([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_USUARIOS_PARA_INSERTARResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_INS_USUARIO")]
		public int PROC_INS_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "USUARIO", DbType = "VarChar(50)")] string uSUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "ROL", DbType = "Int")] System.Nullable<int> rOL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSUARIO, rOL, cIA);
			return ((int)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_INS_ROL")]
		public int PROC_INS_ROL([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "DESCRIPCION", DbType = "VarChar(50)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dESCRIPCION, cIA);
			return ((int)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_EDI_PERMISOS")]
		public int PROC_EDI_PERMISOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "ROL", DbType = "Int")] System.Nullable<int> rOL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "ORDEN_PRODUCCION", DbType = "Int")] System.Nullable<int> oRDEN_PRODUCCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "USUARIOS", DbType = "Int")] System.Nullable<int> uSUARIOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rOL, oRDEN_PRODUCCION, uSUARIOS, cIA);
			return ((int)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_VAL_USUARIO_SOFTLAND")]
		public ISingleResult<PROC_VAL_USUARIO_SOFTLANDResult> PROC_VAL_USUARIO_SOFTLAND([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "USUARIO", DbType = "VarChar(100)")] string uSUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "PASS", DbType = "VarChar(250)")] string pASS)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSUARIO, pASS);
			return ((ISingleResult<PROC_VAL_USUARIO_SOFTLANDResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_VAL_USUARIO")]
		public ISingleResult<PROC_VAL_USUARIOResult> PROC_VAL_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "USUARIO", DbType = "VarChar(100)")] string uSUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "PASS", DbType = "VarChar(250)")] string pASS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSUARIO, pASS, cIA);
			return ((ISingleResult<PROC_VAL_USUARIOResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_VAL_USUARIO_ACTIVO")]
		public ISingleResult<PROC_VAL_USUARIO_ACTIVOResult> PROC_VAL_USUARIO_ACTIVO([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "USUARIO", DbType = "VarChar(50)")] string uSUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSUARIO, cIA);
			return ((ISingleResult<PROC_VAL_USUARIO_ACTIVOResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_OBT_USUARIO_PERMISOS")]
		public ISingleResult<PROC_OBT_USUARIO_PERMISOSResult> PROC_OBT_USUARIO_PERMISOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "ROL", DbType = "Int")] System.Nullable<int> rOL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rOL, cIA);
			return ((ISingleResult<PROC_OBT_USUARIO_PERMISOSResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_VAL_USUARIO_ROL")]
		public ISingleResult<PROC_VAL_USUARIO_ROLResult> PROC_VAL_USUARIO_ROL([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "USUARIO", DbType = "VarChar(50)")] string uSUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSUARIO, cIA);
			return ((ISingleResult<PROC_VAL_USUARIO_ROLResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_OBT_PERMISOS")]
		public ISingleResult<PROC_OBT_PERMISOSResult> PROC_OBT_PERMISOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_PERMISOSResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_OBT_BODEGAS_X_ARTICULO_PARA_SELECCIONAR")]
		public ISingleResult<PROC_OBT_BODEGAS_X_ARTICULO_PARA_SELECCIONARResult> PROC_OBT_BODEGAS_X_ARTICULO_PARA_SELECCIONAR([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "ARTICULO", DbType = "VarChar(20)")] string aRTICULO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aRTICULO, cIA);
			return ((ISingleResult<PROC_OBT_BODEGAS_X_ARTICULO_PARA_SELECCIONARResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_EDI_HORA_FIN_ORDEN_PRODUCCION_LINEA")]
		public int PROC_EDI_HORA_FIN_ORDEN_PRODUCCION_LINEA([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "DOCUMENTO", DbType = "VarChar(50)")] string dOCUMENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "LINEA", DbType = "Int")] System.Nullable<int> lINEA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "HORA_FIN", DbType = "VarChar(5)")] string hORA_FIN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dOCUMENTO, lINEA, hORA_FIN, cIA);
			return ((int)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_EDI_HORA_INICIO_ORDEN_PRODUCCION_LINEA")]
		public int PROC_EDI_HORA_INICIO_ORDEN_PRODUCCION_LINEA([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "DOCUMENTO", DbType = "VarChar(50)")] string dOCUMENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "LINEA", DbType = "Int")] System.Nullable<int> lINEA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "HORA_INICIO", DbType = "VarChar(5)")] string hORA_INICIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dOCUMENTO, lINEA, hORA_INICIO, cIA);
			return ((int)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_INS_ORDEN_PRODUCCION_LINEA")]
		public int PROC_INS_ORDEN_PRODUCCION_LINEA([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "ARTICULO", DbType = "VarChar(50)")] string aRTICULO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "BODEGA", DbType = "VarChar(4)")] string bODEGA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CANTIDAD", DbType = "Decimal(28,8)")] System.Nullable<decimal> cANTIDAD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "HORA_INICIO", DbType = "VarChar(5)")] string hORA_INICIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "HORA_FIN", DbType = "VarChar(5)")] string hORA_FIN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "DOCUMENTO", DbType = "VarChar(50)")] string dOCUMENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "LOCALIZACION", DbType = "VarChar(8)")] string lOCALIZACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aRTICULO, bODEGA, cANTIDAD, hORA_INICIO, hORA_FIN, dOCUMENTO, lOCALIZACION, cIA);
			return ((int)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_OBT_ORDENES_PRODUCCION")]
		public ISingleResult<PROC_OBT_ORDENES_PRODUCCIONResult> PROC_OBT_ORDENES_PRODUCCION([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "FECHA_INICIO", DbType = "VarChar(25)")] string fECHA_INICIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "FECHA_FINAL", DbType = "VarChar(25)")] string fECHA_FINAL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "ORDEN", DbType = "VarChar(50)")] string oRDEN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "ARTICULO", DbType = "VarChar(20)")] string aRTICULO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "BODEGA", DbType = "VarChar(4)")] string bODEGA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "ESTADO", DbType = "VarChar(1)")] string eSTADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "USUARIO", DbType = "VarChar(50)")] string uSUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fECHA_INICIO, fECHA_FINAL, oRDEN, aRTICULO, bODEGA, eSTADO, uSUARIO, cIA);
			return ((ISingleResult<PROC_OBT_ORDENES_PRODUCCIONResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_OBT_ORDENES_PRODUCCION_LINEAS")]
		public ISingleResult<PROC_OBT_ORDENES_PRODUCCION_LINEASResult> PROC_OBT_ORDENES_PRODUCCION_LINEAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "ORDEN", DbType = "VarChar(50)")] string oRDEN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), oRDEN, cIA);
			return ((ISingleResult<PROC_OBT_ORDENES_PRODUCCION_LINEASResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_INS_ORDEN_PRODUCCION")]
		public int PROC_INS_ORDEN_PRODUCCION([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "ARTICULO", DbType = "VarChar(50)")] string aRTICULO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "RECETA", DbType = "VarChar(50)")] string rECETA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "BODEGA", DbType = "VarChar(4)")] string bODEGA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CANTIDAD", DbType = "Decimal(28,8)")] System.Nullable<decimal> cANTIDAD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "HOJAS", DbType = "Decimal(28,8)")] System.Nullable<decimal> hOJAS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "USUARIO", DbType = "VarChar(50)")] string uSUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "REFERENCIA", DbType = "VarChar(200)")] string rEFERENCIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(30)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aRTICULO, rECETA, bODEGA, cANTIDAD, hOJAS, uSUARIO, rEFERENCIA, cIA);
			return ((int)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_OBT_RECETAS_A_PRODUCIR")]
		public ISingleResult<PROC_OBT_RECETAS_A_PRODUCIRResult> PROC_OBT_RECETAS_A_PRODUCIR([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cIA);
			return ((ISingleResult<PROC_OBT_RECETAS_A_PRODUCIRResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_OBT_ORDEN_PRODUCCION")]
		public ISingleResult<PROC_OBT_ORDEN_PRODUCCIONResult> PROC_OBT_ORDEN_PRODUCCION([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "ORDEN", DbType = "VarChar(50)")] string oRDEN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), oRDEN, cIA);
			return ((ISingleResult<PROC_OBT_ORDEN_PRODUCCIONResult>)(result.ReturnValue));
		}

		[global::System.Data.Linq.Mapping.FunctionAttribute(Name = "GLOBAL.PROC_OBT_RECETAS_X_ARTICULO_PARA_SELECCIONAR")]
		public ISingleResult<PROC_OBT_RECETAS_X_ARTICULO_PARA_SELECCIONARResult> PROC_OBT_RECETAS_X_ARTICULO_PARA_SELECCIONAR([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "ARTICULO", DbType = "VarChar(20)")] string aRTICULO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CIA", DbType = "VarChar(20)")] string cIA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aRTICULO, cIA);
			return ((ISingleResult<PROC_OBT_RECETAS_X_ARTICULO_PARA_SELECCIONARResult>)(result.ReturnValue));
		}
	}

	[global::System.Data.Linq.Mapping.TableAttribute(Name = "ATCL.ESTADOS_DEMO")]
	public partial class ESTADOS_DEMO : INotifyPropertyChanging, INotifyPropertyChanged
	{

		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

		private string _ID;

		private string _DESCRIP;

		#region Definiciones de métodos de extensibilidad
		partial void OnLoaded();
		partial void OnValidate(System.Data.Linq.ChangeAction action);
		partial void OnCreated();
		partial void OnIDChanging(string value);
		partial void OnIDChanged();
		partial void OnDESCRIPChanging(string value);
		partial void OnDESCRIPChanged();
		#endregion

		public ESTADOS_DEMO()
		{
			OnCreated();
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ID", DbType = "VarChar(1) NOT NULL", CanBeNull = false, IsPrimaryKey = true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DESCRIP", DbType = "VarChar(100)")]
		public string DESCRIP
		{
			get
			{
				return this._DESCRIP;
			}
			set
			{
				if ((this._DESCRIP != value))
				{
					this.OnDESCRIPChanging(value);
					this.SendPropertyChanging();
					this._DESCRIP = value;
					this.SendPropertyChanged("DESCRIP");
					this.OnDESCRIPChanged();
				}
			}
		}

		public event PropertyChangingEventHandler PropertyChanging;

		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}

		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}

	public partial class PROC_OBT_ORDENES_PRODUCCION_FILTROResult
	{

		private string _DOCUMENTO;

		public PROC_OBT_ORDENES_PRODUCCION_FILTROResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DOCUMENTO", DbType = "VarChar(50)")]
		public string DOCUMENTO
		{
			get
			{
				return this._DOCUMENTO;
			}
			set
			{
				if ((this._DOCUMENTO != value))
				{
					this._DOCUMENTO = value;
				}
			}
		}
	}

	public partial class PROC_OBT_USUARIOS_ORDENES_PRODUCCION_FILTROResult
	{

		private string _USUARIO;

		private string _COMPLETO;

		public PROC_OBT_USUARIOS_ORDENES_PRODUCCION_FILTROResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_USUARIO", DbType = "VarChar(50)")]
		public string USUARIO
		{
			get
			{
				return this._USUARIO;
			}
			set
			{
				if ((this._USUARIO != value))
				{
					this._USUARIO = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_COMPLETO", DbType = "VarChar(200)")]
		public string COMPLETO
		{
			get
			{
				return this._COMPLETO;
			}
			set
			{
				if ((this._COMPLETO != value))
				{
					this._COMPLETO = value;
				}
			}
		}
	}

	public partial class PROC_OBT_SIGUIENTE_CONSECUTIVO_ORDENES_PRODUCCIONResult
	{

		private string _SIGUIENTE_CONSEC;

		public PROC_OBT_SIGUIENTE_CONSECUTIVO_ORDENES_PRODUCCIONResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_SIGUIENTE_CONSEC", DbType = "VarChar(50)")]
		public string SIGUIENTE_CONSEC
		{
			get
			{
				return this._SIGUIENTE_CONSEC;
			}
			set
			{
				if ((this._SIGUIENTE_CONSEC != value))
				{
					this._SIGUIENTE_CONSEC = value;
				}
			}
		}
	}

	public partial class PROC_OBT_BODEGASResult
	{

		private string _BODEGA;

		private string _NOMBRE;

		private string _DESCRIPCION;

		public PROC_OBT_BODEGASResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_BODEGA", DbType = "VarChar(4)")]
		public string BODEGA
		{
			get
			{
				return this._BODEGA;
			}
			set
			{
				if ((this._BODEGA != value))
				{
					this._BODEGA = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NOMBRE", DbType = "VarChar(40)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DESCRIPCION", DbType = "VarChar(50)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
	}

	public partial class PROC_OBT_ARTICULOS_A_PRODUCIRResult
	{

		private string _ARTICULO;

		private string _DESCRIPCION;

		private string _COMPLETO;

		public PROC_OBT_ARTICULOS_A_PRODUCIRResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ARTICULO", DbType = "VarChar(20)")]
		public string ARTICULO
		{
			get
			{
				return this._ARTICULO;
			}
			set
			{
				if ((this._ARTICULO != value))
				{
					this._ARTICULO = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DESCRIPCION", DbType = "VarChar(254)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_COMPLETO", DbType = "VarChar(254)")]
		public string COMPLETO
		{
			get
			{
				return this._COMPLETO;
			}
			set
			{
				if ((this._COMPLETO != value))
				{
					this._COMPLETO = value;
				}
			}
		}
	}

	public partial class PROC_OBT_ULTIMA_ORDEN_PRODUCCIONResult
	{

		private string _DOCUMENTO;

		public PROC_OBT_ULTIMA_ORDEN_PRODUCCIONResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DOCUMENTO", DbType = "VarChar(50)")]
		public string DOCUMENTO
		{
			get
			{
				return this._DOCUMENTO;
			}
			set
			{
				if ((this._DOCUMENTO != value))
				{
					this._DOCUMENTO = value;
				}
			}
		}
	}

	public partial class PROC_OBT_CENTROS_DE_COSTOResult
	{

		private string _CENTRO_COSTO;

		private string _COMPLETO;

		public PROC_OBT_CENTROS_DE_COSTOResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CENTRO_COSTO", DbType = "VarChar(25)")]
		public string CENTRO_COSTO
		{
			get
			{
				return this._CENTRO_COSTO;
			}
			set
			{
				if ((this._CENTRO_COSTO != value))
				{
					this._CENTRO_COSTO = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_COMPLETO", DbType = "VarChar(254)")]
		public string COMPLETO
		{
			get
			{
				return this._COMPLETO;
			}
			set
			{
				if ((this._COMPLETO != value))
				{
					this._COMPLETO = value;
				}
			}
		}
	}

	public partial class PROC_OBT_CUENTAS_CONTABLESResult
	{

		private string _CUENTA_CONTABLE;

		private string _COMPLETO;

		public PROC_OBT_CUENTAS_CONTABLESResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CUENTA_CONTABLE", DbType = "VarChar(25)")]
		public string CUENTA_CONTABLE
		{
			get
			{
				return this._CUENTA_CONTABLE;
			}
			set
			{
				if ((this._CUENTA_CONTABLE != value))
				{
					this._CUENTA_CONTABLE = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_COMPLETO", DbType = "VarChar(254)")]
		public string COMPLETO
		{
			get
			{
				return this._COMPLETO;
			}
			set
			{
				if ((this._COMPLETO != value))
				{
					this._COMPLETO = value;
				}
			}
		}
	}

	public partial class PROC_OBT_ARTICULOS_A_CONSUMIRResult
	{

		private string _ARTICULO;

		private string _COMPLETO;

		public PROC_OBT_ARTICULOS_A_CONSUMIRResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ARTICULO", DbType = "VarChar(20)")]
		public string ARTICULO
		{
			get
			{
				return this._ARTICULO;
			}
			set
			{
				if ((this._ARTICULO != value))
				{
					this._ARTICULO = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_COMPLETO", DbType = "VarChar(254)")]
		public string COMPLETO
		{
			get
			{
				return this._COMPLETO;
			}
			set
			{
				if ((this._COMPLETO != value))
				{
					this._COMPLETO = value;
				}
			}
		}
	}

	public partial class PROC_OBT_CUENTAS_CONTABLES_X_CENTRO_COSTOResult
	{

		private string _CENTRO_COSTO;

		private string _CUENTA_CONTABLE;

		private string _COMPLETO;

		public PROC_OBT_CUENTAS_CONTABLES_X_CENTRO_COSTOResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CENTRO_COSTO", DbType = "VarChar(25)")]
		public string CENTRO_COSTO
		{
			get
			{
				return this._CENTRO_COSTO;
			}
			set
			{
				if ((this._CENTRO_COSTO != value))
				{
					this._CENTRO_COSTO = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CUENTA_CONTABLE", DbType = "VarChar(25)")]
		public string CUENTA_CONTABLE
		{
			get
			{
				return this._CUENTA_CONTABLE;
			}
			set
			{
				if ((this._CUENTA_CONTABLE != value))
				{
					this._CUENTA_CONTABLE = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_COMPLETO", DbType = "VarChar(254)")]
		public string COMPLETO
		{
			get
			{
				return this._COMPLETO;
			}
			set
			{
				if ((this._COMPLETO != value))
				{
					this._COMPLETO = value;
				}
			}
		}
	}

	public partial class PROC_OBT_BODEGAS_X_ARTICULOResult
	{

		private string _BODEGA;

		private string _COMPLETO;

		private System.Nullable<decimal> _EXISTENCIA;

		private string _ARTICULO;

		public PROC_OBT_BODEGAS_X_ARTICULOResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_BODEGA", DbType = "VarChar(4)")]
		public string BODEGA
		{
			get
			{
				return this._BODEGA;
			}
			set
			{
				if ((this._BODEGA != value))
				{
					this._BODEGA = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_COMPLETO", DbType = "VarChar(254)")]
		public string COMPLETO
		{
			get
			{
				return this._COMPLETO;
			}
			set
			{
				if ((this._COMPLETO != value))
				{
					this._COMPLETO = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_EXISTENCIA", DbType = "Decimal(28,2)")]
		public System.Nullable<decimal> EXISTENCIA
		{
			get
			{
				return this._EXISTENCIA;
			}
			set
			{
				if ((this._EXISTENCIA != value))
				{
					this._EXISTENCIA = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ARTICULO", DbType = "VarChar(20)")]
		public string ARTICULO
		{
			get
			{
				return this._ARTICULO;
			}
			set
			{
				if ((this._ARTICULO != value))
				{
					this._ARTICULO = value;
				}
			}
		}
	}

	public partial class PROC_OBT_EXISTENCIAS_X_ARTICULOResult
	{

		private string _BODEGA;

		private System.Nullable<decimal> _EXISTENCIA;

		private string _ARTICULO;

		public PROC_OBT_EXISTENCIAS_X_ARTICULOResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_BODEGA", DbType = "VarChar(4)")]
		public string BODEGA
		{
			get
			{
				return this._BODEGA;
			}
			set
			{
				if ((this._BODEGA != value))
				{
					this._BODEGA = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_EXISTENCIA", DbType = "Decimal(28,2)")]
		public System.Nullable<decimal> EXISTENCIA
		{
			get
			{
				return this._EXISTENCIA;
			}
			set
			{
				if ((this._EXISTENCIA != value))
				{
					this._EXISTENCIA = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ARTICULO", DbType = "VarChar(20)")]
		public string ARTICULO
		{
			get
			{
				return this._ARTICULO;
			}
			set
			{
				if ((this._ARTICULO != value))
				{
					this._ARTICULO = value;
				}
			}
		}
	}

	public partial class PROC_OBT_USUARIOSResult
	{

		private string _USUARIO;

		private string _NOMBRE;

		private System.Nullable<int> _ROL;

		private string _ROL_DESCRIPCION;

		private string _ESTADO;

		public PROC_OBT_USUARIOSResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_USUARIO", DbType = "VarChar(50)")]
		public string USUARIO
		{
			get
			{
				return this._USUARIO;
			}
			set
			{
				if ((this._USUARIO != value))
				{
					this._USUARIO = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NOMBRE", DbType = "VarChar(150)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ROL", DbType = "Int")]
		public System.Nullable<int> ROL
		{
			get
			{
				return this._ROL;
			}
			set
			{
				if ((this._ROL != value))
				{
					this._ROL = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ROL_DESCRIPCION", DbType = "VarChar(50)")]
		public string ROL_DESCRIPCION
		{
			get
			{
				return this._ROL_DESCRIPCION;
			}
			set
			{
				if ((this._ROL_DESCRIPCION != value))
				{
					this._ROL_DESCRIPCION = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ESTADO", DbType = "VarChar(1)")]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
	}

	public partial class PROC_OBT_ROLESResult
	{

		private System.Nullable<int> _ROL;

		private string _DESCRIPCION;

		public PROC_OBT_ROLESResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ROL", DbType = "Int")]
		public System.Nullable<int> ROL
		{
			get
			{
				return this._ROL;
			}
			set
			{
				if ((this._ROL != value))
				{
					this._ROL = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DESCRIPCION", DbType = "VarChar(200)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
	}

	public partial class PROC_OBT_USUARIOS_PARA_INSERTARResult
	{

		private string _USUARIO;

		private string _DESCRIPCION;

		public PROC_OBT_USUARIOS_PARA_INSERTARResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_USUARIO", DbType = "VarChar(50)")]
		public string USUARIO
		{
			get
			{
				return this._USUARIO;
			}
			set
			{
				if ((this._USUARIO != value))
				{
					this._USUARIO = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DESCRIPCION", DbType = "VarChar(100)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
	}

	public partial class PROC_VAL_USUARIO_SOFTLANDResult
	{

		private System.Nullable<int> _VALID;

		public PROC_VAL_USUARIO_SOFTLANDResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_VALID", DbType = "Int")]
		public System.Nullable<int> VALID
		{
			get
			{
				return this._VALID;
			}
			set
			{
				if ((this._VALID != value))
				{
					this._VALID = value;
				}
			}
		}
	}

	public partial class PROC_VAL_USUARIOResult
	{

		private System.Nullable<int> _VALID;

		public PROC_VAL_USUARIOResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_VALID", DbType = "Int")]
		public System.Nullable<int> VALID
		{
			get
			{
				return this._VALID;
			}
			set
			{
				if ((this._VALID != value))
				{
					this._VALID = value;
				}
			}
		}
	}

	public partial class PROC_VAL_USUARIO_ACTIVOResult
	{

		private string _ACTIVO;

		public PROC_VAL_USUARIO_ACTIVOResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ACTIVO", DbType = "VarChar(1)")]
		public string ACTIVO
		{
			get
			{
				return this._ACTIVO;
			}
			set
			{
				if ((this._ACTIVO != value))
				{
					this._ACTIVO = value;
				}
			}
		}
	}

	public partial class PROC_OBT_USUARIO_PERMISOSResult
	{

		private System.Nullable<int> _ROL;

		private string _DESCRIPCION;

		private System.Nullable<int> _ORDEN_PRODUCCION;

		private System.Nullable<int> _USUARIOS;

		public PROC_OBT_USUARIO_PERMISOSResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ROL", DbType = "Int")]
		public System.Nullable<int> ROL
		{
			get
			{
				return this._ROL;
			}
			set
			{
				if ((this._ROL != value))
				{
					this._ROL = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DESCRIPCION", DbType = "VarChar(50)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ORDEN_PRODUCCION", DbType = "Int")]
		public System.Nullable<int> ORDEN_PRODUCCION
		{
			get
			{
				return this._ORDEN_PRODUCCION;
			}
			set
			{
				if ((this._ORDEN_PRODUCCION != value))
				{
					this._ORDEN_PRODUCCION = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_USUARIOS", DbType = "Int")]
		public System.Nullable<int> USUARIOS
		{
			get
			{
				return this._USUARIOS;
			}
			set
			{
				if ((this._USUARIOS != value))
				{
					this._USUARIOS = value;
				}
			}
		}
	}

	public partial class PROC_VAL_USUARIO_ROLResult
	{

		private System.Nullable<int> _ROL;

		private string _DESCRIPCION;

		private string _USUARIO;

		private string _CIA;

		private string _NOMBRE;

		private string _CORREO;

		public PROC_VAL_USUARIO_ROLResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ROL", DbType = "Int")]
		public System.Nullable<int> ROL
		{
			get
			{
				return this._ROL;
			}
			set
			{
				if ((this._ROL != value))
				{
					this._ROL = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DESCRIPCION", DbType = "VarChar(50)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_USUARIO", DbType = "VarChar(50)")]
		public string USUARIO
		{
			get
			{
				return this._USUARIO;
			}
			set
			{
				if ((this._USUARIO != value))
				{
					this._USUARIO = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CIA", DbType = "VarChar(30)")]
		public string CIA
		{
			get
			{
				return this._CIA;
			}
			set
			{
				if ((this._CIA != value))
				{
					this._CIA = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NOMBRE", DbType = "VarChar(150)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CORREO", DbType = "VarChar(255)")]
		public string CORREO
		{
			get
			{
				return this._CORREO;
			}
			set
			{
				if ((this._CORREO != value))
				{
					this._CORREO = value;
				}
			}
		}
	}

	public partial class PROC_OBT_PERMISOSResult
	{

		private System.Nullable<int> _ROL;

		private string _DESCRIPCION;

		private string _ORDEN_PRODUCCION;

		private string _USUARIOS;

		public PROC_OBT_PERMISOSResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ROL", DbType = "Int")]
		public System.Nullable<int> ROL
		{
			get
			{
				return this._ROL;
			}
			set
			{
				if ((this._ROL != value))
				{
					this._ROL = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DESCRIPCION", DbType = "VarChar(50)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ORDEN_PRODUCCION", DbType = "VarChar(1)")]
		public string ORDEN_PRODUCCION
		{
			get
			{
				return this._ORDEN_PRODUCCION;
			}
			set
			{
				if ((this._ORDEN_PRODUCCION != value))
				{
					this._ORDEN_PRODUCCION = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_USUARIOS", DbType = "VarChar(1)")]
		public string USUARIOS
		{
			get
			{
				return this._USUARIOS;
			}
			set
			{
				if ((this._USUARIOS != value))
				{
					this._USUARIOS = value;
				}
			}
		}
	}

	public partial class PROC_OBT_BODEGAS_X_ARTICULO_PARA_SELECCIONARResult
	{

		private string _BODEGA;

		public PROC_OBT_BODEGAS_X_ARTICULO_PARA_SELECCIONARResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_BODEGA", DbType = "VarChar(4)")]
		public string BODEGA
		{
			get
			{
				return this._BODEGA;
			}
			set
			{
				if ((this._BODEGA != value))
				{
					this._BODEGA = value;
				}
			}
		}
	}

	public partial class PROC_OBT_ORDENES_PRODUCCIONResult
	{

		private string _DOCUMENTO;

		private string _ARTICULO;

		private string _ARTICULO_COMPLETO;

		private string _UNIDAD_DE_MEDIDA;

		private System.Nullable<decimal> _HOJAS;

		private string _BODEGA;

		private System.Nullable<decimal> _CANTIDAD;

		private string _REFERENCIA;

		private string _ESTADO;

		private System.Nullable<int> _LINEAS;

		private System.Nullable<System.DateTime> _FECHA;

		private string _FECHA_STR;

		private string _USUARIO;

		private string _APROBADOR;

		private string _FECHA_APROBACION;

		public PROC_OBT_ORDENES_PRODUCCIONResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DOCUMENTO", DbType = "VarChar(50)")]
		public string DOCUMENTO
		{
			get
			{
				return this._DOCUMENTO;
			}
			set
			{
				if ((this._DOCUMENTO != value))
				{
					this._DOCUMENTO = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ARTICULO", DbType = "VarChar(20)")]
		public string ARTICULO
		{
			get
			{
				return this._ARTICULO;
			}
			set
			{
				if ((this._ARTICULO != value))
				{
					this._ARTICULO = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ARTICULO_COMPLETO", DbType = "VarChar(250)")]
		public string ARTICULO_COMPLETO
		{
			get
			{
				return this._ARTICULO_COMPLETO;
			}
			set
			{
				if ((this._ARTICULO_COMPLETO != value))
				{
					this._ARTICULO_COMPLETO = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_UNIDAD_DE_MEDIDA", DbType = "VarChar(6)")]
		public string UNIDAD_DE_MEDIDA
		{
			get
			{
				return this._UNIDAD_DE_MEDIDA;
			}
			set
			{
				if ((this._UNIDAD_DE_MEDIDA != value))
				{
					this._UNIDAD_DE_MEDIDA = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_HOJAS", DbType = "Decimal(28,2)")]
		public System.Nullable<decimal> HOJAS
		{
			get
			{
				return this._HOJAS;
			}
			set
			{
				if ((this._HOJAS != value))
				{
					this._HOJAS = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_BODEGA", DbType = "VarChar(4)")]
		public string BODEGA
		{
			get
			{
				return this._BODEGA;
			}
			set
			{
				if ((this._BODEGA != value))
				{
					this._BODEGA = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CANTIDAD", DbType = "Decimal(28,2)")]
		public System.Nullable<decimal> CANTIDAD
		{
			get
			{
				return this._CANTIDAD;
			}
			set
			{
				if ((this._CANTIDAD != value))
				{
					this._CANTIDAD = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_REFERENCIA", DbType = "VarChar(200)")]
		public string REFERENCIA
		{
			get
			{
				return this._REFERENCIA;
			}
			set
			{
				if ((this._REFERENCIA != value))
				{
					this._REFERENCIA = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ESTADO", DbType = "VarChar(1)")]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_LINEAS", DbType = "Int")]
		public System.Nullable<int> LINEAS
		{
			get
			{
				return this._LINEAS;
			}
			set
			{
				if ((this._LINEAS != value))
				{
					this._LINEAS = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_FECHA", DbType = "DateTime")]
		public System.Nullable<System.DateTime> FECHA
		{
			get
			{
				return this._FECHA;
			}
			set
			{
				if ((this._FECHA != value))
				{
					this._FECHA = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_FECHA_STR", DbType = "VarChar(30)")]
		public string FECHA_STR
		{
			get
			{
				return this._FECHA_STR;
			}
			set
			{
				if ((this._FECHA_STR != value))
				{
					this._FECHA_STR = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_USUARIO", DbType = "VarChar(5)")]
		public string USUARIO
		{
			get
			{
				return this._USUARIO;
			}
			set
			{
				if ((this._USUARIO != value))
				{
					this._USUARIO = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_APROBADOR", DbType = "VarChar(50)")]
		public string APROBADOR
		{
			get
			{
				return this._APROBADOR;
			}
			set
			{
				if ((this._APROBADOR != value))
				{
					this._APROBADOR = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_FECHA_APROBACION", DbType = "VarChar(30)")]
		public string FECHA_APROBACION
		{
			get
			{
				return this._FECHA_APROBACION;
			}
			set
			{
				if ((this._FECHA_APROBACION != value))
				{
					this._FECHA_APROBACION = value;
				}
			}
		}
	}

	public partial class PROC_OBT_ORDENES_PRODUCCION_LINEASResult
	{

		private string _DOCUMENTO_INV;

		private System.Nullable<int> _LINEA;

		private string _ARTICULO;

		private string _ARTICULO_NOMBRE;

		private string _BODEGA;

		private System.Nullable<decimal> _EXISTENCIA;

		private System.Nullable<decimal> _CONSUMIDO;

		private string _CENTRO_COSTO;

		private string _CENTRO_COSTO_NOMBRE;

		private string _CUENTA_CONTABLE;

		private string _CUENTA_CONTABLE_NOMBRE;

		private string _ESTADO;

		private string _APROBADOR;

		private string _HORA_INICIO;

		private string _HORA_FIN;

		private string _TIEMPO_TEORICO;

		public PROC_OBT_ORDENES_PRODUCCION_LINEASResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DOCUMENTO_INV", DbType = "VarChar(50)")]
		public string DOCUMENTO_INV
		{
			get
			{
				return this._DOCUMENTO_INV;
			}
			set
			{
				if ((this._DOCUMENTO_INV != value))
				{
					this._DOCUMENTO_INV = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_LINEA", DbType = "Int")]
		public System.Nullable<int> LINEA
		{
			get
			{
				return this._LINEA;
			}
			set
			{
				if ((this._LINEA != value))
				{
					this._LINEA = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ARTICULO", DbType = "VarChar(20)")]
		public string ARTICULO
		{
			get
			{
				return this._ARTICULO;
			}
			set
			{
				if ((this._ARTICULO != value))
				{
					this._ARTICULO = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ARTICULO_NOMBRE", DbType = "VarChar(254)")]
		public string ARTICULO_NOMBRE
		{
			get
			{
				return this._ARTICULO_NOMBRE;
			}
			set
			{
				if ((this._ARTICULO_NOMBRE != value))
				{
					this._ARTICULO_NOMBRE = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_BODEGA", DbType = "VarChar(4)")]
		public string BODEGA
		{
			get
			{
				return this._BODEGA;
			}
			set
			{
				if ((this._BODEGA != value))
				{
					this._BODEGA = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_EXISTENCIA", DbType = "Decimal(28,8)")]
		public System.Nullable<decimal> EXISTENCIA
		{
			get
			{
				return this._EXISTENCIA;
			}
			set
			{
				if ((this._EXISTENCIA != value))
				{
					this._EXISTENCIA = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CONSUMIDO", DbType = "Decimal(28,8)")]
		public System.Nullable<decimal> CONSUMIDO
		{
			get
			{
				return this._CONSUMIDO;
			}
			set
			{
				if ((this._CONSUMIDO != value))
				{
					this._CONSUMIDO = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CENTRO_COSTO", DbType = "VarChar(25)")]
		public string CENTRO_COSTO
		{
			get
			{
				return this._CENTRO_COSTO;
			}
			set
			{
				if ((this._CENTRO_COSTO != value))
				{
					this._CENTRO_COSTO = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CENTRO_COSTO_NOMBRE", DbType = "VarChar(200)")]
		public string CENTRO_COSTO_NOMBRE
		{
			get
			{
				return this._CENTRO_COSTO_NOMBRE;
			}
			set
			{
				if ((this._CENTRO_COSTO_NOMBRE != value))
				{
					this._CENTRO_COSTO_NOMBRE = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CUENTA_CONTABLE", DbType = "VarChar(25)")]
		public string CUENTA_CONTABLE
		{
			get
			{
				return this._CUENTA_CONTABLE;
			}
			set
			{
				if ((this._CUENTA_CONTABLE != value))
				{
					this._CUENTA_CONTABLE = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CUENTA_CONTABLE_NOMBRE", DbType = "VarChar(200)")]
		public string CUENTA_CONTABLE_NOMBRE
		{
			get
			{
				return this._CUENTA_CONTABLE_NOMBRE;
			}
			set
			{
				if ((this._CUENTA_CONTABLE_NOMBRE != value))
				{
					this._CUENTA_CONTABLE_NOMBRE = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ESTADO", DbType = "VarChar(1)")]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_APROBADOR", DbType = "VarChar(50)")]
		public string APROBADOR
		{
			get
			{
				return this._APROBADOR;
			}
			set
			{
				if ((this._APROBADOR != value))
				{
					this._APROBADOR = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_HORA_INICIO", DbType = "VarChar(30)")]
		public string HORA_INICIO
		{
			get
			{
				return this._HORA_INICIO;
			}
			set
			{
				if ((this._HORA_INICIO != value))
				{
					this._HORA_INICIO = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_HORA_FIN", DbType = "VarChar(30)")]
		public string HORA_FIN
		{
			get
			{
				return this._HORA_FIN;
			}
			set
			{
				if ((this._HORA_FIN != value))
				{
					this._HORA_FIN = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TIEMPO_TEORICO", DbType = "VarChar(30)")]
		public string TIEMPO_TEORICO
		{
			get
			{
				return this._TIEMPO_TEORICO;
			}
			set
			{
				if ((this._TIEMPO_TEORICO != value))
				{
					this._TIEMPO_TEORICO = value;
				}
			}
		}
	}

	public partial class PROC_OBT_RECETAS_A_PRODUCIRResult
	{

		private string _RECETA;

		private string _DESCRIPCION;

		private string _COMPLETO;

		public PROC_OBT_RECETAS_A_PRODUCIRResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_RECETA", DbType = "VarChar(20)")]
		public string RECETA
		{
			get
			{
				return this._RECETA;
			}
			set
			{
				if ((this._RECETA != value))
				{
					this._RECETA = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DESCRIPCION", DbType = "VarChar(254)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_COMPLETO", DbType = "VarChar(254)")]
		public string COMPLETO
		{
			get
			{
				return this._COMPLETO;
			}
			set
			{
				if ((this._COMPLETO != value))
				{
					this._COMPLETO = value;
				}
			}
		}
	}

	public partial class PROC_OBT_ORDEN_PRODUCCIONResult
	{

		private string _DOCUMENTO;

		private string _REFERENCIA;

		private string _ESTADO;

		private System.Nullable<int> _LINEAS;

		private System.Nullable<System.DateTime> _FECHA;

		private string _FECHA_STR;

		private string _FECHA_STR_SIN_HORAS;

		private string _USUARIO;

		private string _ARTICULO;

		private string _RECETA;

		private System.Nullable<decimal> _CANTIDAD;

		private string _BODEGA;

		private System.Nullable<decimal> _HOJAS;

		public PROC_OBT_ORDEN_PRODUCCIONResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DOCUMENTO", DbType = "VarChar(50)")]
		public string DOCUMENTO
		{
			get
			{
				return this._DOCUMENTO;
			}
			set
			{
				if ((this._DOCUMENTO != value))
				{
					this._DOCUMENTO = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_REFERENCIA", DbType = "VarChar(200)")]
		public string REFERENCIA
		{
			get
			{
				return this._REFERENCIA;
			}
			set
			{
				if ((this._REFERENCIA != value))
				{
					this._REFERENCIA = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ESTADO", DbType = "VarChar(1)")]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_LINEAS", DbType = "Int")]
		public System.Nullable<int> LINEAS
		{
			get
			{
				return this._LINEAS;
			}
			set
			{
				if ((this._LINEAS != value))
				{
					this._LINEAS = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_FECHA", DbType = "DateTime")]
		public System.Nullable<System.DateTime> FECHA
		{
			get
			{
				return this._FECHA;
			}
			set
			{
				if ((this._FECHA != value))
				{
					this._FECHA = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_FECHA_STR", DbType = "VarChar(30)")]
		public string FECHA_STR
		{
			get
			{
				return this._FECHA_STR;
			}
			set
			{
				if ((this._FECHA_STR != value))
				{
					this._FECHA_STR = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_FECHA_STR_SIN_HORAS", DbType = "VarChar(30)")]
		public string FECHA_STR_SIN_HORAS
		{
			get
			{
				return this._FECHA_STR_SIN_HORAS;
			}
			set
			{
				if ((this._FECHA_STR_SIN_HORAS != value))
				{
					this._FECHA_STR_SIN_HORAS = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_USUARIO", DbType = "VarChar(5)")]
		public string USUARIO
		{
			get
			{
				return this._USUARIO;
			}
			set
			{
				if ((this._USUARIO != value))
				{
					this._USUARIO = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ARTICULO", DbType = "VarChar(20)")]
		public string ARTICULO
		{
			get
			{
				return this._ARTICULO;
			}
			set
			{
				if ((this._ARTICULO != value))
				{
					this._ARTICULO = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_RECETA", DbType = "VarChar(20)")]
		public string RECETA
		{
			get
			{
				return this._RECETA;
			}
			set
			{
				if ((this._RECETA != value))
				{
					this._RECETA = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CANTIDAD", DbType = "Decimal(28,2)")]
		public System.Nullable<decimal> CANTIDAD
		{
			get
			{
				return this._CANTIDAD;
			}
			set
			{
				if ((this._CANTIDAD != value))
				{
					this._CANTIDAD = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_BODEGA", DbType = "VarChar(4)")]
		public string BODEGA
		{
			get
			{
				return this._BODEGA;
			}
			set
			{
				if ((this._BODEGA != value))
				{
					this._BODEGA = value;
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_HOJAS", DbType = "Decimal(28,2)")]
		public System.Nullable<decimal> HOJAS
		{
			get
			{
				return this._HOJAS;
			}
			set
			{
				if ((this._HOJAS != value))
				{
					this._HOJAS = value;
				}
			}
		}
	}

	public partial class PROC_OBT_RECETAS_X_ARTICULO_PARA_SELECCIONARResult
	{

		private string _RECETA;

		public PROC_OBT_RECETAS_X_ARTICULO_PARA_SELECCIONARResult()
		{
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_RECETA", DbType = "VarChar(250)")]
		public string RECETA
		{
			get
			{
				return this._RECETA;
			}
			set
			{
				if ((this._RECETA != value))
				{
					this._RECETA = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
